@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor #FEFCE8
  BorderColor #92400E
  ArrowColor #78350F
}
skinparam actor {
  BorderColor #78350F
}

actor "Pengguna" as U

rectangle "Autentikasi" {
  usecase "UC-01\nLogin" as UC01
  usecase "UC-02\nRegister" as UC02
  usecase "UC-03\nLogout" as UC03
  usecase "UC-04\nLogin Biometrik" as UC04
  usecase "UC-05\nSetup PIN" as UC05
  usecase "UC-06\nHash Password" as UC06
  usecase "UC-07\nKelola Session JWT" as UC07
}

U --> UC01
U --> UC02
U --> UC03

UC01 ..> UC06 : <<include>>
UC01 ..> UC07 : <<include>>
UC02 ..> UC06 : <<include>>
UC02 ..> UC07 : <<include>>
UC04 ..> UC07 : <<include>>
UC01 <.. UC04 : <<extend>>
UC01 <.. UC05 : <<extend>>
@enduml
